version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - crypto_network

  worker:
    build: .
    command: celery -A crypto_trading.celery_config worker --pool=solo -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
    networks:
      - crypto_network

  app:
    build: .
    command: python main.py
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
    networks:
      - crypto_network

networks:
  crypto_network:
    driver: bridge